### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by dylanirlbeck** [pckilgore/bs-biginteger#3]
I tried adding this as a dependency to a new project but was getting an error because I didn't have `big-integer` added as a dependency. I think most binding libraries have the corresponding JS library as a dependency (not a peer dependency, as you have), so this might be worth updating. I also might not have installed correctly, so let me know if that's the case!

**Comment by pckilgore** [comment]
BigInteger.js is explicitly listed as a peer dependency.  You should see a warning about this from your package manager on installation.

There's a variety of arguments on either side of what type of dependency a library should be to a set of reason bindings, I prefer peer for the flexibility. 

If the community settles on a different standard these bindings will adjust but for now, closing as won't fix.
